ignoredBuiltDependencies:
  - '@apollo/protobufjs'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - cbor-extract
  - cpu-features
  - protobufjs
  - sqlite3
  - ssh2

overrides:
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
