import { BinaryMessageSignatureVerificationRequestDto } from '../signature/BinaryMessageSignatureVerificationRequestDto';

export class WalletBinarySignatureVerificationRequestDto extends BinaryMessageSignatureVerificationRequestDto {}